/**
 * Shape of the `/data/config.json` file generated by `stats.py`.
 */
export interface RaceConfig {
  /**
   * Focus athlete name in "Last, First" format.
   */
  readonly athlete: string

  /**
   * Hyrox season number.
   */
  readonly season: number

  /**
   * Race location identifier (e.g. `"Washington-DC"`).
   */
  readonly location: string

  /**
   * Gender category (`"male"` or `"female"`).
   */
  readonly gender: string

  /**
   * Division name (e.g. `"open"`, `"pro"`, `"doubles"`).
   */
  readonly division: string
}
